//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class social_media_individual
    {
        public int sm_ind_id { get; set; }
        public int indid { get; set; }
        public int sm_type { get; set; }
        public byte[] sm_link { get; set; }
        public string sm_title { get; set; }
    
        public virtual individual individual { get; set; }
        public virtual sm_types sm_types { get; set; }
    }
}
