//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sunshinedataEntities : DbContext
    {
        public sunshinedataEntities()
            : base("name=sunshinedataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actions_individual> actions_individual { get; set; }
        public virtual DbSet<actions_organization> actions_organization { get; set; }
        public virtual DbSet<addresses_individual> addresses_individual { get; set; }
        public virtual DbSet<addresses_organization> addresses_organization { get; set; }
        public virtual DbSet<individual> individuals { get; set; }
        public virtual DbSet<officer> officers { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
        public virtual DbSet<phonenumbers_individual> phonenumbers_individual { get; set; }
        public virtual DbSet<phonenumbers_organization> phonenumbers_organization { get; set; }
        public virtual DbSet<sm_types> sm_types { get; set; }
        public virtual DbSet<social_media_individual> social_media_individual { get; set; }
        public virtual DbSet<social_media_organization> social_media_organization { get; set; }
    }
}
