//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary.IndividualsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class phonenumber
    {
        public long ownerID { get; set; }
        public string phone { get; set; }
        public bool primary { get; set; }
    
        public virtual individual individual { get; set; }
    }
}
